# SELECT CATEGORY, COUNT(*) AS TOTAL_SALES
# FROM BOOK
# JOIN BOOK_SALES
# USING(BOOK_ID)
# WHERE SALES_DATE LIKE '2022-01-%'
# GROUP BY CATEGORY, BOOK_ID
# ORDER BY CATEGORY;

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK
JOIN BOOK_SALES
USING(BOOK_ID)
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY;